name: opentelemetry_sdk
description: Dart port of the OpenTelemetry SDK tracing implementation.
version: 0.1.0
publish_to: none
resolution: workspace
environment:
  sdk: ">=3.6.0 <4.0.0"
dependencies:
  collection: ^1.18.0
  meta: ^1.10.0
  opentelemetry_api:
    path: ../opentelemetry_api
  opentelemetry_shared:
    path: ../opentelemetry_shared
dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
